//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormState.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormState.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///  &lt;!-- no point in putting anything here --&gt;
        ///  &lt;!-- Make sure this file is an EmbeddedResource --&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  &lt;p&gt;See you went to an additional page, woot - I don&apos;t know why you&apos;d want to do this, but I thought I should or could support it.&lt;/p&gt;
        ///  &lt;p&gt;Since this window can scroll forever I&apos;d suggest not even using additional pages. Copy and paste works!&lt;/p&gt;
        ///  &lt;p&gt;&lt;a href=&apos;frmAbout&apos;&gt;Go Back&lt;/a&gt; - Can we go back?&lt;/p&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string Additional {
            get {
                return ResourceManager.GetString("Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///  &lt;!-- no point in putting anything here --&gt;
        ///  &lt;!-- Make sure this file is an EmbeddedResource --&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  &lt;p&gt;You will notice that this form doesn&apos;t have a matching white background like the rest of the forms you&apos;ve seen. It also doesn&apos;t have an about button. This is because this form decends from Form and not frmBase.&lt;/p&gt;
        ///  &lt;p&gt;But it is still handled properly by the state machine&lt;/p&gt;
        ///  &lt;p&gt;&lt;a href=&apos;Additional&apos;&gt;Test&lt;/a&gt; - You can load up another document here (if it&apos;s in  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frmAbout {
            get {
                return ResourceManager.GetString("frmAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///  &lt;!-- no point in putting anything here. It&apos;s all replaced by an embedded CSS file --&gt;
        ///  &lt;!-- Make sure this file is an EmbeddedResource --&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  &lt;p&gt;You should not see this form. It is only used to set properties that all inherited forms will use.&lt;/p&gt;
        ///  &lt;p&gt;If it is visible it is just for demonstration purposes.&lt;/p&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string frmBase {
            get {
                return ResourceManager.GetString("frmBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///  &lt;!-- no point in putting anything here. It&apos;s all replaced by an embedded CSS file --&gt;
        ///  &lt;!-- Make sure this file is an EmbeddedResource --&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  &lt;p&gt;Not much help here&lt;/p&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string frmFour {
            get {
                return ResourceManager.GetString("frmFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///  &lt;!-- no point in putting anything here --&gt;
        ///  &lt;!-- Make sure this file is an EmbeddedResource --&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  &lt;p&gt;This is a tech demo to show off a handy state machine&lt;/p&gt;
        ///  &lt;p&gt;An application can have state, and users can navigate every which way through an application&lt;/p&gt;
        ///  &lt;p&gt;It is the state machine&apos;s job to keep track of that so the programmer can focus on application logic and not navigation&lt;/p&gt;
        ///  &lt;p&gt;As you click on the buttons you will be taken to a new screen (or form [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frmLogin {
            get {
                return ResourceManager.GetString("frmLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///  &lt;!-- no point in putting anything here. It&apos;s all replaced by an embedded CSS file --&gt;
        ///  &lt;!-- Make sure this file is an EmbeddedResource --&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  &lt;p&gt;Not much help here&lt;/p&gt;
        ///  &lt;p&gt;But there is another line&lt;/p&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string frmThree {
            get {
                return ResourceManager.GetString("frmThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///  &lt;!-- no point in putting anything here --&gt;
        ///  &lt;!-- Make sure this file is an EmbeddedResource --&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  &lt;p&gt;The first form you saw only had a big button to load up this screen (The about button is actually owned by the base form).&lt;/p&gt;
        ///  &lt;p&gt;This form has two different buttons that take the user down two different paths. The back button (which is now enabled) will take you back the way you came.&lt;/p&gt;
        ///  &lt;p&gt;The challenge without a state machine is keeping track of where the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frmTwo {
            get {
                return ResourceManager.GetString("frmTwo", resourceCulture);
            }
        }
    }
}
